Enhance error handling for missing pdftotext dependency and update README with usage examples and goals

diff --git a/42pdf b/42pdf
--- a/42pdf
+++ b/42pdf
@@ -41,6 +41,13 @@ check_errors() {
 		echo "Too many arguments"
 		exit 1
 	fi
+	if ! command -v pdftotext &> /dev/null; then
+		echo "pdftotext is required but not installed. Do you want to install it now? (Ctrl+C to exit)"
+		sudo apt-get update && sudo apt-get install -y poppler-utils
+		if [ $? -eq 1 ]; then
+			exit 0
+		fi
+	fi
 }
 
 search_and_download_by_name() {
@@ -210,3 +217,6 @@ main() {
 
 check_errors "$@"
 main "$@"
+
+# cmd to download pack: all (+1gb)
+# cat pdf_db.txt | cut -d' ' -f2- | sort | uniq > uniq_db.txt
